import { Category } from "./types";

// GuidedCaptureRunner's config surface — the primitives it actually
// understands, and nothing more. Per the founder-fit audit: this list was
// originally just what Switch, DJI, and PS5 already did (instruction,
// camera_capture as a burst or a single shot, product_photo, review,
// submit). GoPro's Bluetooth read stays on its own hand-written flow —
// nothing else needs it yet. Digicam's file-upload path was ALSO
// hand-written originally; "file-upload" is now a real runner step type
// (see below) so other categories can reuse it declaratively instead of
// forking a whole new flow component.
//
// ONE-PHONE SELLER PRINCIPLE (evidence-UX doctrine, added in the
// one-phone-seller-evidence pass): a seller should never need a second
// phone, a second tablet, a borrowed screen, or a handwritten/printed
// TestPass code just to produce evidence. The normal setup is the
// seller's own phone + the product being sold + whatever that product
// ordinarily needs to operate (printer paper, a console's usual
// TV/controller, its own network). TestPass itself must never manufacture
// a new hardware dependency. Two structural tools this file gives every
// category to honor that:
//   1. "file-upload" steps — for evidence that already lives in an app on
//      the SAME phone (a manufacturer app's own screen). The seller
//      switches apps, takes a native OS screenshot, switches back, and
//      picks that file — never photographs one phone with another.
//   2. Session-bound live-camera capture — every "single-capture" and
//      "countdown-burst" shot is already timestamped and tied to this
//      session by the server that receives it (see submit/route.ts's
//      serverReceivedAt). That's what proves a live capture is fresh; a
//      seller no longer needs to hold a physical code in the frame to
//      prove the same thing, and categories should prefer dropping a held
//      code over asking for a second display to show it on.
// A "file-upload" step's evidence is honestly weaker on capture-freshness
// than a live camera capture (a screenshot could in principle be older
// than the session), and category configs must say so in their
// evaluationPromptSystem rather than let it inherit live-capture strength.
//
// Four permanent doctrine rules added in the physical-feasibility +
// error-recovery pass (round 2 of the one-phone-seller-evidence audit),
// binding on every category's config and every seller-facing string:
//
//   1. ONE-PHONE SELLER PRINCIPLE (restated above) — seller's own phone +
//      the product + the product's ordinary operating dependencies. Never
//      a second device, borrowed screen, or physical code held up to a
//      camera.
//
//   2. EVIDENCE SURFACE RULE — before writing a step, classify where the
//      evidence physically exists, then pick the primitive that matches:
//        A. On the product itself / its normal operating display → the
//           seller's phone LIVE CAMERA ("single-capture"/"countdown-burst").
//        B. On the SAME PHONE running TestPass, inside another app (a
//           manufacturer app, a casting/companion app) → a phone cannot
//           photograph itself, so this is a NATIVE SCREENSHOT handed off
//           via "file-upload" — never TestPass's camera pointed at TestPass.
//        C. Generated BY the product itself (e.g. a digicam's own photo)
//           → audit how that file actually reaches this phone; don't
//           assume frictionless transfer.
//        D. From a machine interface directly → direct BLE/telemetry, only
//           called "direct" after a real, parsed response — see GoPro.
//
//   3. CAPTURE CORRECTION PRINCIPLE — every individual evidence step must
//      be correctable immediately, before advancing; final review is a
//      SECOND safety net, never the first chance to fix a bad capture.
//      Single live-camera capture: capture → preview → Retake | Use photo,
//      no auto-advance (see pendingSingle/confirmSingle below). File
//      upload: choose → preview the exact file → Choose different | Use,
//      no auto-advance on selection (pendingFile/confirmFile). Multi-file
//      steps get independent Replace controls per file — replacing one
//      must never delete another. Bluetooth/telemetry: success gets "Use
//      this device" / "Connect a different device"; failure gets "Try
//      again" / "Use photo test" — a failed direct read must never be
//      forced into fallback with no recovery choice (see GoProFlow's
//      bluetooth-result phase). Final review keeps an Edit/Retake/Replace
//      affordance per item that returns to exactly that item without
//      resetting unrelated already-confirmed evidence (see editingStepId /
//      beginEditStep).
//
//   4. ATOMIC EVIDENCE PRINCIPLE — when several frames collectively
//      establish liveness/continuity (a countdown burst, a live
//      print/ejection sequence, a Selftest movement sequence), they are
//      ONE evidence object, not several independently-replaceable ones.
//      The seller can only Redo the entire sequence or Use it as captured
//      (see pendingBurst/confirmBurst) — never swap a single inconvenient
//      frame out of the middle while keeping the rest, which would let a
//      fabricated continuity claim survive a real discontinuity (the
//      Anderson/Farid distinction this is named for).
//
// Doctrine test for every step, before it ships: physically narrate it
// from the seller's point of view — what are they holding, what are they
// looking at, what takes this picture, what happens if they mess it up,
// what proves this is the same physical device, and what does this
// evidence actually prove? A step that fails any of those questions is
// wrong at the mechanic, not the copy.

export interface CaptureShot {
  stepId: string;
  label: string;
  base64: string;
  capturedAt: number;
  // How this shot was produced. Defaults to "live_camera" (the runner's
  // own getUserMedia capture) when omitted by older call sites.
  // "screenshot_upload" is a file-upload step's picked file — the same-phone
  // companion-app path. Categories must reflect this honestly in their
  // evaluator prompt: a screenshot proves less about capture freshness than
  // a live capture, even though both are equally session-bound in storage.
  method?: "live_camera" | "screenshot_upload";
}

export type RunnerStep =
  | {
      type: "countdown-burst";
      id: string;
      label: string;
      shotCount: number;
      intervalMs: number;
      countdownSeconds: number;
      capturingMessage: string;
      // JPEG quality passed to canvas.toDataURL — preserves each original
      // flow's tuning (e.g. Switch's burst used 0.82) rather than forcing
      // one value on every step. Defaults applied by the runner if omitted.
      quality?: number;
    }
  | {
      type: "single-capture";
      id: string;
      label: string;
      // Shown above the camera before this step's capture. Receives the
      // challenge code (if the category uses one) so instructions can
      // reference it without every category re-implementing interpolation.
      instructionText: (challenge: string | null) => string;
      buttonLabel: string;
      quality?: number;
    }
  | {
      // Same-phone companion-app evidence: no camera involved in this step
      // at all. The seller does something in ANOTHER app already on this
      // phone (open a manufacturer app, cast, screenshot), then comes back
      // to TestPass and picks that file from their own photo library — the
      // same file-picker pattern DigicamFlow already used, generalized so
      // any category can declare it instead of hand-writing a whole flow.
      // Never require the seller to leave this phone to produce the file.
      type: "file-upload";
      id: string;
      label: string;
      // Most file-upload categories (DJI, Quest) don't use a challenge code
      // at all — a plain string is fine. NAS is the exception: its
      // same-phone DSM screenshot only means anything if DSM was just
      // renamed to this session's one-time code, so its instructions need
      // to reference the code the seller is about to leave this tab to go
      // use. Accepting the same (challenge) => string shape single-capture
      // steps use, rather than adding a second field, keeps every step
      // type's instructionText interchangeable.
      instructionText: string | ((challenge: string | null) => string);
      pickerLabel: string;
    };

export interface RunnerPrepareConfig {
  // Render config.sellerInstructions (from primitives.ts) as the standard
  // numbered list, exactly like the pre-runner Switch/DJI screens did.
  showStandardInstructions: boolean;
  // PS5-style richer prepare screen: an optional intro card and a bulleted
  // "before you start" list, shown in addition to (or instead of) the
  // standard instructions.
  introTitle?: string;
  introDescription?: string;
  notes?: string[];
  // Shown under the one-time challenge code itself (only relevant when
  // useChallenge is set) — e.g. PS5's "how to actually rename the console"
  // instructions, which are specific to the challenge, not the general
  // prepare notes above.
  challengeHint?: string;
  buttonLabel: string;
}

export interface RunnerSubmissionContent {
  context: string;
  rawData: Record<string, unknown>;
}

export interface RunnerConfig {
  category: Category;
  steps: RunnerStep[];
  // One-time challenge code (e.g. PS5's console-rename code). Generated
  // client-side, after hydration, exactly like the original PS5Flow fix —
  // see GuidedCaptureRunner for why this can't happen during render.
  useChallenge?: boolean;
  challengePrefix?: string;
  prepare: RunnerPrepareConfig;
  includeProductPhoto: boolean;
  productPhotoDeviceLabel?: string;
  filenamePrefix: string;
  // Shown on the review screen, above Retake/Submit — for a claim-boundary
  // note like PS5's "this doesn't certify the console's complete
  // condition." Category-specific messaging, not a generic runner string.
  reviewNote?: string;
  // Original flows didn't all use the same submit wording (PS5: "Submit
  // experiment") — preserved per-category rather than forcing a generic
  // "Submit" everywhere. There is no equivalent per-category retake label
  // any more: CAPTURE CORRECTION PRINCIPLE moved retaking to per-step
  // Retake/Redo/Choose-different controls (see beginEditStep), so the one
  // remaining review-screen reset button is a full "start over completely"
  // escape hatch, not a category-specific action — it gets the same
  // de-emphasized generic label everywhere on purpose.
  submitButtonLabel?: string;
  // Category-specific evidence meaning stays here, not in the runner: the
  // runner hands back the raw shots/challenge/timing, and each category
  // decides what context string the evaluator sees and what raw_data means.
  buildSubmission: (args: {
    shots: CaptureShot[];
    productPhoto: string | null;
    challenge: string | null;
    startedAt: number;
  }) => RunnerSubmissionContent;
}
